In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/dataset.txt',sep='\t')
df.columns = ['a1','a2','a3','a4','a5','a6','d1','d2']
df.index = range(0,119)
df = df.reindex(columns=sorted(df.columns))
df

a1   a2   a3   a4   a5   a6   d1   d2
0    35,9   no   no  yes  yes  yes  yes   no
1    35,9   no  yes   no   no   no   no   no
2    36,0   no   no  yes  yes  yes  yes   no
3    36,0   no  yes   no   no   no   no   no
4    36,0   no  yes   no   no   no   no   no
..    ...  ...  ...  ...  ...  ...  ...  ...
114  41,4   no  yes  yes   no  yes   no  yes
115  41,5   no   no   no   no   no   no   no
116  41,5  yes  yes   no  yes   no   no  yes
117  41,5   no  yes  yes   no  yes   no  yes
118  41,5   no  yes  yes   no  yes   no  yes

[119 rows x 8 columns]

In [ ]:
for i in range(0,119):
  df['a1'][i] = float(df['a1'][i][:2]) + float(df['a1'][i][3:])/10

df

a1   a2   a3   a4   a5   a6   d1   d2
0    35.9   no   no  yes  yes  yes  yes   no
1    35.9   no  yes   no   no   no   no   no
2      36   no   no  yes  yes  yes  yes   no
3      36   no  yes   no   no   no   no   no
4      36   no  yes   no   no   no   no   no
..    ...  ...  ...  ...  ...  ...  ...  ...
114  41.4   no  yes  yes   no  yes   no  yes
115  41.5   no   no   no   no   no   no   no
116  41.5  yes  yes   no  yes   no   no  yes
117  41.5   no  yes  yes   no  yes   no  yes
118  41.5   no  yes  yes   no  yes   no  yes

[119 rows x 8 columns]

In [ ]:
for i in df.columns[1:]:
  for j in range(0,119):
    if df[i][j] == 'yes':
      df[i][j] = 1
    else:
      df[i][j] = 0

df

a1 a2 a3 a4 a5 a6 d1 d2
0    35.9  0  0  1  1  1  1  0
1    35.9  0  1  0  0  0  0  0
2      36  0  0  1  1  1  1  0
3      36  0  1  0  0  0  0  0
4      36  0  1  0  0  0  0  0
..    ... .. .. .. .. .. .. ..
114  41.4  0  1  1  0  1  0  1
115  41.5  0  0  0  0  0  0  0
116  41.5  1  1  0  1  0  0  1
117  41.5  0  1  1  0  1  0  1
118  41.5  0  1  1  0  1  0  1

[119 rows x 8 columns]

In [ ]:
df.to_csv('data.csv')

In [ ]:
X = df[df.columns[:6]]
Y = df[df.columns[6:]]

In [ ]:
#normalizing the dataset
X['a1'] = X['a1']/max(X['a1'])

X

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


a1 a2 a3 a4 a5 a6
0    0.86506  0  0  1  1  1
1    0.86506  0  1  0  0  0
2    0.86747  0  0  1  1  1
3    0.86747  0  1  0  0  0
4    0.86747  0  1  0  0  0
..       ... .. .. .. .. ..
114  0.99759  0  1  1  0  1
115        1  0  0  0  0  0
116        1  1  1  0  1  0
117        1  0  1  1  0  1
118        1  0  1  1  0  1

[119 rows x 6 columns]

In [ ]:
print(X)
print(Y)

          a1 a2 a3 a4 a5 a6
0    0.86506  0  0  1  1  1
1    0.86506  0  1  0  0  0
2    0.86747  0  0  1  1  1
3    0.86747  0  1  0  0  0
4    0.86747  0  1  0  0  0
..       ... .. .. .. .. ..
114  0.99759  0  1  1  0  1
115        1  0  0  0  0  0
116        1  1  1  0  1  0
117        1  0  1  1  0  1
118        1  0  1  1  0  1

[119 rows x 6 columns]
    d1 d2
0    1  0
1    0  0
2    1  0
3    0  0
4    0  0
..  .. ..
114  0  1
115  0  0
116  0  1
117  0  1
118  0  1

[119 rows x 2 columns]


In [ ]:
x_train = X[:101]
x_test = X[101:]
y_train = Y[:101]
y_test = Y[101:]

In [ ]:
print(x_train)
print(y_test)

           a1 a2 a3 a4 a5 a6
0     0.86506  0  0  1  1  1
1     0.86506  0  1  0  0  0
2     0.86747  0  0  1  1  1
3     0.86747  0  1  0  0  0
4     0.86747  0  1  0  0  0
..        ... .. .. .. .. ..
96   0.983133  0  1  1  0  1
97   0.985542  1  1  1  1  0
98   0.985542  1  1  1  1  0
99   0.985542  0  1  1  0  1
100  0.987952  1  1  1  1  1

[101 rows x 6 columns]
    d1 d2
101  0  0
102  0  1
103  0  1
104  1  1
105  1  1
106  0  0
107  0  1
108  0  1
109  1  1
110  0  0
111  0  1
112  0  1
113  1  1
114  0  1
115  0  0
116  0  1
117  0  1
118  0  1


# **Single hidden layer**

In [ ]:
class ANN():
  def __init__(self,input_size,hidden_size,output_size,data_len):
    self.input_size = input_size
    self.hidden_size = hidden_size
    self.output_size = output_size
    self.m = data_len
    self.weight1 = np.random.randn(self.input_size,self.hidden_size)
    self.weight2 = np.random.randn(self.hidden_size,self.output_size)

  def sigmoid(self,X,deriv = False):
      if deriv:
        return X*(1-X)
      else:
        return 1/(1+np.exp(X))

  def feed_forward(self,X):
    self.o1 = np.dot(X,self.weight1).astype(float)
    self.s1 = self.sigmoid(self.o1)
    self.o2 = np.dot(self.s1,self.weight2).astype(float)
    self.s2 = self.sigmoid(self.o2)
    return self.s2,self.s1

  def loss(self,y,output):
    loss = 0
    for i in range(len(output)):
      loss += -(y_test.iloc[i][0]*np.log(output[0][i][0]) + (1-y_test.iloc[i][0])*(1-np.log(output[0][i][0])))
      loss += -(y_test.iloc[i][1]*np.log(output[0][i][1]) + (1-y_test.iloc[i][1])*(1-np.log(output[0][i][1])))

    return loss
    
  def back_prop(self,x,y,output_y,lr = 0.4):
    #print(output_y)
    #print(y)
    self.dz2 = output_y - y
    #print(self.dz2)
    self.dw2 = (1/self.m)*np.dot(self.s1.T,self.dz2)
    #print(self.weight2.shape)
    #print(self.dz2.shape)
    #print(self.weight2.dot(self.dz2).shape)
    self.dz1 = self.weight2.dot(self.dz2.T).T*self.s1*(1-self.s1)
    self.dw1 = (1/self.m)*np.dot(self.dz1.T,x).T

    self.weight2 = self.weight2 - lr*self.dw2
    self.weight1 = self.weight1 - lr*self.dw1

    return self.weight2,self.weight1

  def train(self,x,y):
    output = self.feed_forward(np.array(x[:]))
    w2,w1 = self.back_prop(np.array(x[:]),np.array(y[:]),output[0])
    loss = self.loss(np.array(y[:]),output)
    return loss,w2,w1

In [ ]:
model = ANN(6,7,2,101)
output = model.feed_forward(np.array(x_train[:]))
w2,w1 = model.back_prop(np.array(x_train[:]),np.array(y_train[:]),output[0])

In [ ]:
print(w2)
print(w1)

[[-0.5661731804991897 -0.7462313750365169]
 [-0.1693351217938721 2.1592082899051883]
 [0.10637813660930011 0.005276467259015229]
 [0.500356174605151 0.055536756322884295]
 [-2.1102464849646423 0.017091581203558328]
 [1.1710382891543052 -0.15913925203562343]
 [-0.7717261091014211 -0.012394925454233523]]
[[-0.007593562222621706 0.4380342562897211 0.06139805975780379
  -0.335531081389286 -1.14198357919443 -1.1923426377326098
  -0.1537693165622211]
 [0.6627311145159053 2.3512812504082894 -0.256557472914523
  1.1678445055475366 0.29320197654839236 2.162467045903771
  -1.3317813911113217]
 [1.2478888615183763 -0.7564319370495227 -0.34209393440600755
  -1.4855605058890802 -0.4519039291730813 -0.7366553892935063
  -0.43855290068850383]
 [1.1250372957377053 -1.9376185627853086 0.5646428740581937
  -1.4924683686952638 -0.7552429878530061 -0.4075089891493989
  -0.11654018917717708]
 [1.522392502967889 0.6904193861293545 0.3684498113030947
  2.0259256852950007 1.4815139138605193 -1.19386973433282


In [ ]:
model = ANN(6,7,2,101)
output = model.feed_forward(np.array(x_train[:]))
w2,w1 = model.back_prop(np.array(x_train[:]),np.array(y_train[:]),output[0])

In [ ]:
print(w2)
print(w1)

[[-0.7139761536468557 -0.5483397449842917]
 [-1.3035130920336986 -0.5353911565276415]
 [-1.6217722400096781 0.051290947237478415]
 [-0.3290505629474745 1.200545116103558]
 [0.20020077664311509 -0.35920549362214205]
 [-0.9515008737333142 -1.0684211323402604]
 [-0.7565428008649177 0.6723390877702683]]
[[0.7199851467508391 -0.881121747992615 2.7910107935160275
  -0.16120384848213537 -0.26030822389871966 0.8782570345720678
  -0.03231145537440812]
 [0.07628285899314195 0.8698086975158905 -1.2954178199015367
  2.445176470129634 1.8288631218640417 -0.3513794638943372
  -0.0929447144218003]
 [-0.44650126972266907 -2.195295969943826 -0.2817577551787862
  0.6627237145129402 -0.5379509507213843 -1.9808376209853418
  -0.9423342999826411]
 [-0.8588978112535587 -0.19110879442842868 0.6869653125589616
  0.5274908890730491 -0.6057379485855097 -1.794598531964287
  -0.3139780944875929]
 [-2.5585012442171067 0.339094423628889 -1.7676584935005755
  1.0467730384555012 -0.06590415799197616 -0.23407615090804

In [ ]:
model = ANN(6,7,2,101)
output = model.feed_forward(np.array(x_train[:]))
w2,w1 = model.back_prop(np.array(x_train[:]),np.array(y_train[:]),output[0])

In [ ]:
print(w2,w1)

[[-0.49285334093057875 0.39870065818810374]
 [0.14419540016422058 0.35958177914547684]
 [-1.0018588065722347 0.38371933211616693]
 [0.3558693442258898 0.968801947841239]
 [0.6758308030717242 0.07189290582174362]
 [-0.8787449988259686 0.03397962844673087]
 [2.602432525968315 -1.4411550016449786]] [[1.6879039708834955 0.9343494159961462 -0.09795435659266519
  -0.292024295725212 -0.28683890166210185 0.14898549395935545
  0.8738590225270276]
 [0.5124072422653253 0.4418069819204186 1.1182520767629438
  -1.1097107451348218 -0.8800473282866941 0.4762708007056569
  0.25420192545871684]
 [-0.3359701712121203 1.0836594651451976 0.10686972615330943
  -1.7318024237868337 -1.0319282519466435 -1.287252361427897
  0.26840618224870977]
 [-1.52845016654103 0.3227124924635949 -0.35761100229783077
  0.391354864442577 -2.2961250302716767 1.4896290088974902
  0.4885377315987552]
 [-0.04787570546155226 0.25908948035267937 -1.0267905920709344
  1.3177046410344053 -0.37484335957559634 1.232726630371526
  -1.0

In [ ]:
print(w2.shape)
print(w1.shape)

(7, 2)
(6, 7)


In [ ]:
n_epochs = 50
model1 = ANN(6,7,2,119)
for i in range(n_epochs):
  result = model1.train(x_train,y_train)
  print("Epoch:-",i," Loss:-",result[0])


Epoch:- 0  Loss:- -3.724730754524902
Epoch:- 1  Loss:- -3.7086581368500404
Epoch:- 2  Loss:- -3.6895459764381577
Epoch:- 3  Loss:- -3.6670141023261493
Epoch:- 4  Loss:- -3.6405442337375544
Epoch:- 5  Loss:- -3.6095213743896215
Epoch:- 6  Loss:- -3.57337102307281
Epoch:- 7  Loss:- -3.531797572652063
Epoch:- 8  Loss:- -3.485058642283202
Epoch:- 9  Loss:- -3.4341184647609433
Epoch:- 10  Loss:- -3.3804899667526485
Epoch:- 11  Loss:- -3.325718370364931
Epoch:- 12  Loss:- -3.2707951240042705
Epoch:- 13  Loss:- -3.215956789919171
Epoch:- 14  Loss:- -3.160935487159096
Epoch:- 15  Loss:- -3.105297708876715
Epoch:- 16  Loss:- -3.048621423675579
Epoch:- 17  Loss:- -2.990540795258275
Epoch:- 18  Loss:- -2.9307592445229926
Epoch:- 19  Loss:- -2.869084155212843
Epoch:- 20  Loss:- -2.805491883486144
Epoch:- 21  Loss:- -2.740210382312209
Epoch:- 22  Loss:- -2.673799418957658
Epoch:- 23  Loss:- -2.6072084184512683
Epoch:- 24  Loss:- -2.541795336798831
Epoch:- 25  Loss:- -2.4792933190340283
Epoch:- 26  

In [ ]:
output = model1.feed_forward(np.array(x_test[:]))
print(output[0])

[[0.9206702  0.05748998]
 [0.72204014 0.19664112]
 [0.58501017 0.33965077]
 [0.62178223 0.36764126]
 [0.68119087 0.25718263]
 [0.9203272  0.05778163]
 [0.72143093 0.19721924]
 [0.58479957 0.33988205]
 [0.62141086 0.36803137]
 [0.91998368 0.05807385]
 [0.72082261 0.197797  ]
 [0.58458962 0.34011264]
 [0.68010518 0.25830049]
 [0.58417161 0.34057172]
 [0.91895004 0.05895388]
 [0.71900312 0.19952806]
 [0.58396355 0.34080023]
 [0.58396355 0.34080023]]


In [ ]:
print(y_test)

    d1 d2
101  0  0
102  0  1
103  0  1
104  1  1
105  1  1
106  0  0
107  0  1
108  0  1
109  1  1
110  0  0
111  0  1
112  0  1
113  1  1
114  0  1
115  0  0
116  0  1
117  0  1
118  0  1


In [ ]:
print("testing loss:- ",model1.loss(np.array(y_test[:]),output))

testing loss:-  -4.638097611106936


# **Double hidden layer**

In [ ]:
class ANN():
  def __init__(self,input_size,hidden_size1,hidden_size2,output_size,data_len):
    self.input_size = input_size
    self.hidden_size1 = hidden_size1
    self.hidden_size2 = hidden_size2
    self.output_size = output_size
    self.m = data_len
    self.weight1 = np.random.randn(self.input_size,self.hidden_size1)
    self.weight2 = np.random.randn(self.hidden_size1,self.hidden_size2)
    self.weight3 = np.random.randn(self.hidden_size2,self.output_size)

  def sigmoid(self,X,deriv = False):
      if deriv:
        return X*(1-X)
      else:
        return 1/(1+np.exp(X))

  def feed_forward(self,X):
    self.o1 = np.dot(X,self.weight1).astype(float)
    self.s1 = self.sigmoid(self.o1)
    self.o2 = np.dot(self.s1,self.weight2).astype(float)
    self.s2 = self.sigmoid(self.o2)
    self.o3 = np.dot(self.s2,self.weight3).astype(float)
    self.s3 = self.sigmoid(self.o3)
    return self.s3,self.s2,self.s1

  def loss(self,y,output):
    loss = 0
    for i in range(len(output)):
      loss += -(y_test.iloc[i][0]*np.log(output[0][i][0]) + (1-y_test.iloc[i][0])*(1-np.log(output[0][i][0])))
      loss += -(y_test.iloc[i][1]*np.log(output[0][i][1]) + (1-y_test.iloc[i][1])*(1-np.log(output[0][i][1])))

    return loss
    
  def back_prop(self,x,y,output_y,lr = 0.4):
    #print(output_y)
    #print(y)
    self.dz3 = output_y - y
    #print(self.dz2)
    self.dw3 = (1/self.m)*np.dot(self.s2.T,self.dz3)
    #print(self.weight2.shape)
    #print(self.dz2.shape)
    #print(self.weight2.dot(self.dz2).shape)
    
    self.dz2 = self.weight3.dot(self.dz3.T).T*self.s2*(1-self.s2)
    self.dw2 = (1/self.m)*np.dot(self.dz2.T,self.s1).T

    self.dz1 = self.weight2.dot(self.dz2.T).T*self.s1*(1-self.s1)
    self.dw1 = (1/self.m)*np.dot(self.dz1.T,x).T

    self.weight3 = self.weight3 - lr*self.dw3
    self.weight2 = self.weight2 - lr*self.dw2
    self.weight1 = self.weight1 - lr*self.dw1

    return self.weight3,self.weight2,self.weight1

  def train(self,x,y):
    output = self.feed_forward(np.array(x[:]))
    w3,w2,w1 = self.back_prop(np.array(x[:]),np.array(y[:]),output[0])
    loss = self.loss(np.array(y[:]),output)
    return loss,w3,w2,w1

In [ ]:
model = ANN(6,5,10,2,101)
output = model.feed_forward(np.array(x_train[:]))
w3,w2,w1 = model.back_prop(np.array(x_train[:]),np.array(y_train[:]),output[0])

In [ ]:
print(w3)
print(w2)
print(w1)

[[1.2082520809107928 -0.051010578138441856]
 [0.7062151164301553 0.36386095167818744]
 [1.3389598458594698 1.087058358940139]
 [-0.2520260810063547 1.1323651814645852]
 [1.3667655360884268 1.0485391157739445]
 [0.22331894067135322 -0.794603190341136]
 [-0.34328859583430016 -1.9361775578694567]
 [0.6210710621498006 -1.4684487634366414]
 [1.2640714323119981 -0.5658442434059489]
 [-0.4267071486775792 -0.8284195683064222]]
[[-1.0264772438497844 0.6377951692377318 -2.043537100367106
  -0.0007845440564735948 0.7320548718344567 -0.48342371124551864
  0.1582635757686744 1.05591317108125 -2.626931312892883
  -0.7895895286625852]
 [1.9900756466101384 -0.031889702125056506 1.9749077365104146
  -1.4735806698928509 0.7132761587520389 -0.8516058760863405
  -0.618341565536789 1.0601718906239868 0.2776280631166508
  -1.1643871456590822]
 [-0.7400607574071433 -0.026163187188043727 0.07465954882390671
  -0.6397781654025912 -0.6739213148495541 1.1564820946658332
  -1.1596099132781286 -0.7914556318077062 

In [ ]:
print(w3.shape)
print(w2.shape)
print(w1.shape)

(10, 2)
(5, 10)
(6, 5)


In [ ]:
model = ANN(6,5,10,2,101)
output = model.feed_forward(np.array(x_train[:]))
w3,w2,w1 = model.back_prop(np.array(x_train[:]),np.array(y_train[:]),output[0])

In [ ]:
print(w3)
print(w2)
print(w1)

[[1.1718368012212634 -0.6054725600174885]
 [1.2342635523739116 -1.0546708437607537]
 [-0.6546652090310191 -1.3382987457116369]
 [0.38909297140600224 -0.7927914974201804]
 [-0.6001852555722871 -1.3126764870429972]
 [-0.22619027264915148 1.0790961873883909]
 [-0.24435666075675563 -1.2365471911925077]
 [0.8210033244527324 0.0004524181717733]
 [-0.3912008935604595 0.054304485517526146]
 [0.19096480691615103 1.2177120667968078]]
[[-0.7948912559629504 -0.4473736717031441 0.35875116838690496
  -0.7721870710060514 0.14669364346230557 -1.01248779146306
  0.11602869847062132 -1.469392900145189 -0.47160602623282133
  -0.7767848823368232]
 [0.559638386814092 -0.7204189756818405 0.3272939075129706
  1.325861963117641 -2.6694698903798906 -0.9368415314338552
  -0.4187855244912974 -0.11300926537600872 1.0736470779353464
  -1.262549501049864]
 [0.7124120400502443 -1.1221206966267387 0.9086107886231605
  0.20312044052782954 -0.7217002597478728 1.527958713775026
  -0.3297885848144718 0.17986553824090287 

In [ ]:
model = ANN(6,5,10,2,101)
output = model.feed_forward(np.array(x_train[:]))
w3,w2,w1 = model.back_prop(np.array(x_train[:]),np.array(y_train[:]),output[0])

In [ ]:
print(w3)
print(w2)
print(w1)

[[1.2082520809107928 -0.051010578138441856]
 [0.7062151164301553 0.36386095167818744]
 [1.3389598458594698 1.087058358940139]
 [-0.2520260810063547 1.1323651814645852]
 [1.3667655360884268 1.0485391157739445]
 [0.22331894067135322 -0.794603190341136]
 [-0.34328859583430016 -1.9361775578694567]
 [0.6210710621498006 -1.4684487634366414]
 [1.2640714323119981 -0.5658442434059489]
 [-0.4267071486775792 -0.8284195683064222]]
[[-1.0264772438497844 0.6377951692377318 -2.043537100367106
  -0.0007845440564735948 0.7320548718344567 -0.48342371124551864
  0.1582635757686744 1.05591317108125 -2.626931312892883
  -0.7895895286625852]
 [1.9900756466101384 -0.031889702125056506 1.9749077365104146
  -1.4735806698928509 0.7132761587520389 -0.8516058760863405
  -0.618341565536789 1.0601718906239868 0.2776280631166508
  -1.1643871456590822]
 [-0.7400607574071433 -0.026163187188043727 0.07465954882390671
  -0.6397781654025912 -0.6739213148495541 1.1564820946658332
  -1.1596099132781286 -0.7914556318077062 

In [ ]:
n_epochs = 50
model2 = ANN(6,5,10,2,120)
for i in range(n_epochs):
  result = model2.train(x_train,y_train)
  print("Epoch:-",i," Loss:-",result[0])


Epoch:- 0  Loss:- -4.3560579645622495
Epoch:- 1  Loss:- -4.307020013928691
Epoch:- 2  Loss:- -4.259189804286
Epoch:- 3  Loss:- -4.214889082074143
Epoch:- 4  Loss:- -4.176306713309287
Epoch:- 5  Loss:- -4.1448925316234435
Epoch:- 6  Loss:- -4.12078569011467
Epoch:- 7  Loss:- -4.102664615042545
Epoch:- 8  Loss:- -4.08830761149033
Epoch:- 9  Loss:- -4.0756468232610095
Epoch:- 10  Loss:- -4.063593594517667
Epoch:- 11  Loss:- -4.052096414386723
Epoch:- 12  Loss:- -4.041622808419596
Epoch:- 13  Loss:- -4.0326269612220775
Epoch:- 14  Loss:- -4.025309417822723
Epoch:- 15  Loss:- -4.019624012385725
Epoch:- 16  Loss:- -4.015380014524206
Epoch:- 17  Loss:- -4.012341314052167
Epoch:- 18  Loss:- -4.010292852011562
Epoch:- 19  Loss:- -4.009079113723723
Epoch:- 20  Loss:- -4.008627905840615
Epoch:- 21  Loss:- -4.008966126354808
Epoch:- 22  Loss:- -4.010207279791512
Epoch:- 23  Loss:- -4.012429266979227
Epoch:- 24  Loss:- -4.0153543107539935
Epoch:- 25  Loss:- -4.018080491859678
Epoch:- 26  Loss:- -4.

In [ ]:
output = model2.feed_forward(np.array(x_test[:]))

In [ ]:
print("testing loss:- ",model2.loss(np.array(y_test[:]),output))

testing loss:-  -4.000001701939577
